### ISSUE TITLE
Raise exception or continue with error logs?

### ISSUE THREAD

**Issue by Nelly-Barret** [Nelly-Barret/BETTER-fairificator#88]

**Comment by Nelly-Barret** [comment]
Some discussions here: https://www.reddit.com/r/learnpython/comments/9l0aqb/when_should_i_use_loggererror_vs_raise_exception/

**Comment by Nelly-Barret** [comment]
For now, I think it is better to handle exceptions, i.e., write log messages instead of throwing stacktrace. But **when the ETL ends, it should file a report with what went wrong (if applicable)**

**Comment by Nelly-Barret** [comment]
A good combination is to do it as follows:

```python
try:
    bla bla
except ServerSelectionTimeoutError as e:
    log.error(e)
    return
```

This allows to log a pretty error (instead of the stack trace) and to not continue the program (which who fail, unless we put `is not None` condition almost everywhere). Returning is also better than `exit` because exit completely terminates the program, which make the tests fail (as they are trying to check whether the code borke as expected or not)

**Comment by Nelly-Barret** [comment]
The above comment does work but is not very satisfying because:
- when the function returns `None`, i.e., is a method, we cannot know if we returned because of an error or because the method has finished
- to overcome this, one could make all methods become boolean functions returning `True` when no error is raised, `False` otherwise. However, this would considerably overcomplicate the code.

A better solution is to:
- raise Exceptions **with a user-friendly text** in the code
- put a `try/except` around the main and print the exception (previsouly raised, so with the user-friendly text)

**Comment by Nelly-Barret** [comment]
I adopted the above-mentioned approach (raise exceptions when something is wrong, use a `try/except` in the main). Closing the issue; this has been implemented together with other fixes in https://github.com/Nelly-Barret/BETTER-fairificator/pull/92

**Comment by Nelly-Barret** [comment]
The only problem is that I cannot trace where the exception comes from: it says it comes from the main, even if this is not true.

For now, I have:
```python
2024-07-03:15:40:47, ERROR [main:<module>:64] TypeError exception (main.py L57): 'NoneType' object is not subscriptable
```

I can also add `raise` in the `try/except` in the main in order to print the stack trace an dI obtain more details:
```python
2024-07-03:15:40:47, ERROR [main:<module>:64] TypeError exception (main.py L57): 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/nelly/Documents/boulot/postdoc-polimi/BETTER-fairificator/src/main.py", line 57, in <module>
    etl.run()
  File "/Users/nelly/Documents/boulot/postdoc-polimi/BETTER-fairificator/src/etl/ETL.py", line 63, in run
    self._extract.run()
  File "/Users/nelly/Documents/boulot/postdoc-polimi/BETTER-fairificator/src/etl/Extract.py", line 31, in run
    self.load_metadata_file()
  File "/Users/nelly/Documents/boulot/postdoc-polimi/BETTER-fairificator/src/etl/Extract.py", line 57, in load_metadata_file
    log.debug(f"{self._metadata[MetadataColumns.DATASET_NAME.value].unique()}")
                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
